name: Deployment Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:
  build_and_test:
    runs-on: ubuntu-18.04
    env:
      SECRET: ${{ secrets.SECRET }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: install packages
        run: npm install && cd client && npm install
      - name: lint code
        run: npm run eslint
      - name: jest test
        run: npm run test
      - name: build frontend
        run: npm run build-client
      - name: e2e test with cypress
        uses: cypress-io/github-action@v2
        with:
          start: npm run start-test
          command: npm run cypress:run
          wait-on: http://localhost:3001