name: Deployment Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET: ${{ secrets.SECRET }}
      TEST_MONGODB_URL: ${{ secrets.TEST_MONGODB_URL }}
      PRODUCTION_MONGODB_URL: ${{ secrets.PRODUCTION_MONGODB_URL }}
      DEV_MONGODB_URL: ${{ secrets.DEV_MONGODB_URL }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: install packages
        run: npm install && cd client && npm install
      - name: lint code
        run: npm run eslint
      - name: jest test
        run: npm run test
      - name: e2e test with cypress
        uses: cypress-io/github-action@v2
        with:
          start: npm run start-test
          command: npm run cypress:run
          wait-on: http://localhost:3001
      - name: build client
        run: npm run build-client
      - name: deploy_to_heroku
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
        uses: akhileshns/heroku-deploy@v3.11.10
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "listablog"
          heroku_email: "datog309@gmail.com"
          healthcheck: "http://listablog.herokuapp.com/healthcheck"
          checkstring: "works"
          rollbackonhealthcheckfailed: true
  tagging:
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch